"""Add automation_events table

Revision ID: 6739745bdf57
Revises: ef873be02e79
Create Date: 2026-05-04 19:06:57.690187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "6739745bdf57"
down_revision: Union[str, Sequence[str], None] = "ef873be02e79"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "automation_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("stage", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("outcome", sa.String(), nullable=False),
        sa.Column("supplier_thread_id", sa.Integer(), nullable=True),
        sa.Column("detail", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "action IN ('send_inquiry', 'read_messages', 'send_reply')",
            name="check_automation_action",
        ),
        sa.CheckConstraint(
            "outcome IN ('deterministic', 'agent_fallback', 'failed')",
            name="check_automation_outcome",
        ),
        sa.CheckConstraint(
            "stage IN ('s3_outreach', 's4_inbox', 's5_negotiation')",
            name="check_automation_stage",
        ),
        sa.ForeignKeyConstraint(
            ["supplier_thread_id"],
            ["supplier_threads.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("automation_events")
    # ### end Alembic commands ###
