"""Split product into two tables, source product and supplier product

Revision ID: 775631f2aaa9
Revises: a3a4a63a0c35
Create Date: 2026-05-01 15:55:10.459945

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "775631f2aaa9"
down_revision: Union[str, Sequence[str], None] = "a3a4a63a0c35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("specs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "supplier_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source_product_id", sa.Integer(), nullable=False),
        sa.Column("supplier_id", sa.Integer(), nullable=False),
        sa.Column("platform", sa.String(), nullable=False),
        sa.Column("product_url", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("specs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("price", sa.String(), nullable=True),
        sa.Column("moq", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "platform IN ('alibaba', 'globalsources')",
            name="check_supplier_product_platform",
        ),
        sa.ForeignKeyConstraint(
            ["source_product_id"],
            ["source_products.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supplier_id"],
            ["suppliers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_url"),
    )
    op.add_column(
        "supplier_threads", sa.Column("source_product_id", sa.Integer(), nullable=False)
    )
    op.add_column(
        "supplier_threads",
        sa.Column("supplier_product_id", sa.Integer(), nullable=False),
    )
    op.drop_constraint(op.f("uq_product_supplier"), "supplier_threads", type_="unique")
    op.create_unique_constraint(
        "uq_source_supplier_product",
        "supplier_threads",
        ["source_product_id", "supplier_product_id"],
    )
    op.drop_constraint(
        op.f("supplier_threads_product_id_fkey"), "supplier_threads", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "supplier_threads", "supplier_products", ["supplier_product_id"], ["id"]
    )
    op.create_foreign_key(
        None, "supplier_threads", "source_products", ["source_product_id"], ["id"]
    )
    op.drop_column("supplier_threads", "product_id")
    op.drop_table("products")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("source_url", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "specs",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("products_pkey")),
        sa.UniqueConstraint(
            "source_url",
            name=op.f("products_source_url_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.add_column(
        "supplier_threads",
        sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "supplier_threads", type_="foreignkey")
    op.drop_constraint(None, "supplier_threads", type_="foreignkey")
    op.create_foreign_key(
        op.f("supplier_threads_product_id_fkey"),
        "supplier_threads",
        "products",
        ["product_id"],
        ["id"],
    )
    op.drop_constraint("uq_source_supplier_product", "supplier_threads", type_="unique")
    op.create_unique_constraint(
        op.f("uq_product_supplier"),
        "supplier_threads",
        ["product_id", "supplier_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("supplier_threads", "supplier_product_id")
    op.drop_column("supplier_threads", "source_product_id")
    op.drop_table("supplier_products")
    op.drop_table("source_products")
    # ### end Alembic commands ###
