"""Add supplier unique constraints and business_type, is_verified columns

Revision ID: a3a4a63a0c35
Revises: 8c4d86931179
Create Date: 2026-05-01 01:08:50.378532

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a3a4a63a0c35"
down_revision: Union[str, Sequence[str], None] = "8c4d86931179"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_product_supplier", "supplier_threads", ["product_id", "supplier_id"]
    )
    op.add_column("suppliers", sa.Column("business_type", sa.String(), nullable=True))
    op.add_column(
        "suppliers",
        sa.Column("is_verified", sa.Boolean(), server_default="false", nullable=False),
    )
    op.create_unique_constraint("uq_supplier_profile_url", "suppliers", ["profile_url"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_supplier_profile_url", "suppliers", type_="unique")
    op.drop_column("suppliers", "is_verified")
    op.drop_column("suppliers", "business_type")
    op.drop_constraint("uq_product_supplier", "supplier_threads", type_="unique")
    # ### end Alembic commands ###
