"""Add match_status, match_confidence, match_reason to supplier_products

Revision ID: ef873be02e79
Revises: 06e7fb7357a1
Create Date: 2026-05-04 13:44:04.938914

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "ef873be02e79"
down_revision: Union[str, Sequence[str], None] = "06e7fb7357a1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "supplier_products",
        sa.Column(
            "match_status", sa.String(), server_default="pending", nullable=False
        ),
    )
    op.add_column(
        "supplier_products",
        sa.Column("match_confidence", sa.Numeric(precision=3, scale=2), nullable=True),
    )
    op.add_column(
        "supplier_products", sa.Column("match_reason", sa.String(), nullable=True)
    )
    op.create_check_constraint(
        "check_match_status",
        "supplier_products",
        "match_status IN ('pending', 'matched', 'rejected')",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("check_match_status", "supplier_products", type_="check")
    op.drop_column("supplier_products", "match_reason")
    op.drop_column("supplier_products", "match_confidence")
    op.drop_column("supplier_products", "match_status")
    # ### end Alembic commands ###
